Own your business data
Manifesto
The data generated by a business should be owned by this business for its own and its customers benefits. 

Principles
#Own data warehouse over vendor locked in
#Central warehouse rather than silos 
#Open, transferable data format over vendor proprietary
#De-coupled warehouse, ETL and business analysis tool over monolith
#Open-source over proprietary 



Notes
#Own warehouse doesn’t necessary mean owned physical infrastructure, use of AWS, Azure or other cloud infrastructure is fine as long as you have a plan of how can you move out if required
